#!/usr/bin/env python3
"""Turn src/CGMBootstrap.js into src/CGMBootstrap.generated.h (C string literal)."""
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "src", "CGMBootstrap.js")
DST = os.path.join(ROOT, "src", "CGMBootstrap.generated.h")
CHUNK = 3000


def main():
    with open(SRC, "rb") as fh:
        raw = fh.read()
    text = raw.decode("utf-8")
    out = ["/* auto-generated by tools/embed_js.py - do not edit */",
           "#ifndef CGM_BOOTSTRAP_JS_H",
           "#define CGM_BOOTSTRAP_JS_H",
           "static const char kCGMBootstrapJS[] ="]
    for i in range(0, len(text), CHUNK):
        part = text[i:i + CHUNK]
        esc = (part.replace("\\", "\\\\")
                   .replace('"', '\\"')
                   .replace("\r", "")
                   .replace("\n", "\\n")
                   .replace("\t", "\\t"))
        out.append('  "%s"' % esc)
    out.append(";")
    out.append("#endif")
    out.append("")
    with open(DST, "w", encoding="utf-8", newline="\n") as fh:
        fh.write("\n".join(out))
    print("generated %s (%d bytes of JS)" % (DST, len(raw)))
    return 0


if __name__ == "__main__":
    sys.exit(main())